favoriteDrink: coffee2

mosquitto:
  service:
    name: mosquitto

appserver:
  service:
    name: chirpstack-as

networkserver:
  service: 
    name: chirpstack-ns

postgresql:
  service:
    name: pgsql

redis:
  service:
    name: redis
  spec:
    volumeClaimTemplates:
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 50M


exporter:
  redis:
    service:
      name: redis-exporter