apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mosquitto.service.name | default "mosquitto"  }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: mosquitto
spec:
  ports:
    - port: 1883
      name: mosquitto
  type: ClusterIP
  selector:
    app: mosquitto
