apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mosquitto
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: mosquitto
  serviceName: "mosquitto"
  replicas: 1
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      terminationGracePeriodSeconds: 30 #default 30
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:1.6.12 #2.0.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1883
          name: mosquitto

