apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.service.name | default "pgsql"  }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: pgsql
spec:
  ports:
    - port: 5432
      name: pgsql
  type: ClusterIP
  selector:
    app: pgsql
