apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgsql
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: pgsql
  serviceName: "pgsql"
  replicas: 1
  template:
    metadata:
      labels:
        app: pgsql
    spec:
      terminationGracePeriodSeconds: 30 #default 30
      containers:
      - name: pgsql
        image: postgres:9.6-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
          name: pgsql
#        envFrom:
#          - configMapRef:
#              name: postgres-config
        volumeMounts:
        - name: pginit
          mountPath: /docker-entrypoint-initdb.d
        - name: pgsql-pvc
          mountPath: /var/lib/postgresql/data
          subPath: postgres
      volumes:
      - name: pginit
        configMap:
          name: {{ .Release.Name }}-postgres-init
  volumeClaimTemplates:
  - metadata:
      name: pgsql-pvc
    spec:
      accessModes: {{ .Values.redis.spec.volumeClaimTemplates.spec.accessModes }} #["ReadWriteOnce"]
      storageClassName: {{ .Values.redis.spec.volumeClaimTemplates.spec.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.redis.spec.volumeClaimTemplates.spec.resources.requests.storage }}
