apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.exporter.redis.service.name | default "redis-exporter"  }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: redis-exporter
spec:
  ports:
    - port: 9121
      name: redis-exporter
  type: ClusterIP
  selector:
    app: redis-exporter
