apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appserver.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chirpstack.standardLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: chirpstack-as
      {{- include "chirpstack.matchLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        app: chirpstack-as
        {{- include "chirpstack.template.labels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 30
      initContainers:
      - name: wait-redis
        image: busybox:1.31
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nslookup {{ .Values.redis.service.name }}; do echo waiting for redis; sleep 2; done;']
      - name: wait-mqtt
        image: busybox:1.31
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nslookup {{ .Values.mosquitto.service.name }}; do echo waiting for mqtt; sleep 2; done;']
      - name: wait-postgresql
        image: busybox:1.31
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nslookup {{ .Values.postgresql.service.name }}; do echo waiting for postgresql; sleep 2; done;']
      containers:
      - name: chirpstack-as
        image: chirpstack/chirpstack-application-server:3
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: configfile
          mountPath: /etc/chirpstack-application-server
        ports:
        - name: chirpstack-as
          containerPort: 8080
      volumes:
      - name: configfile
        configMap:
          name:  {{ .Release.Name}}-as-configmap