apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appserver.service.name | default "chirpstack-as"  }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chirpstack.matchLabels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      name: chirpstack-as
  type: LoadBalancer
  selector:
    {{- include "chirpstack.matchLabels" . | nindent 4 }}
